app/models.py
from datetime import datetime

from flask_login import UserMixin, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), nullable=False, unique=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def set_password(self, password):
        pass_hash = generate_password_hash(password)
        self.password = pass_hash

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f'User: {self.username}'


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(user_id)


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    user_id = db.Column(db.String, nullable=False)
    post = db.Column(db.String, nullable=False)
    comment = db.relationship('Comment', backref='post', lazy='dynamic')
    category = db.Column(db.String, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    up_vote = db.relationship('Upvote', backref='post', lazy='dynamic')
    down_vote = db.relationship('Downvote', backref='post', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Post Title: {self.title}"


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)
    comment = db.Column(db.Text())

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post_id):
        comments = Comment.query.filter_by(post_id=post_id).all()
        return comments

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Comments: {self.comment}'


class Upvote(db.Model):
    __tablename__ = 'upvotes'
    id = db.Column(db.Integer, primary_key=True)
    upvote = db.Column(db.Integer, default=1)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def upvote(cls, id):
        upvote_post = Upvote(user=current_user, post_id=id)
        upvote_post.save()

    @classmethod
    def query_upvotes(cls, id):
        upvote = Upvote.query.filter_by(post_id=id).all()
        return upvote

    @classmethod
    def all_upvotes(cls):
        upvotes = Upvote.query.order_by('id').all()
        return upvotes

    def __repr__(self):
        return f'{self.user_id}:{self.post_id}'


class Downvote(db.Model):
    __tablename__ = 'downvotes'
    id = db.Column(db.Integer, primary_key=True)
    downvote = db.Column(db.Integer, default=1)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def downvote(cls, id):
        downvote_post = Downvote(user=current_user, post_id=id)
        downvote_post.save()

    @classmethod
    def query_downvotes(cls, id):
        downvote = Downvote.query.filter_by(post_id=id).all()
        return downvote

    @classmethod
    def all_downvotes(cls):
        downvote = Downvote.query.order_by('id').all()
        return downvote

    def __repr__(self):
        return f'{self.user_id}:{self.post_id}'

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from config import config_options


# from config import Config


db = SQLAlchemy()
login_manager = LoginManager()
bootstrap = Bootstrap()
mail = Mail()
login_manager.login_view = 'auth.login'
login_manager.session_protection = 'strong'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    login_manager.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from .views import *
 

app/main/views.py
from flask import render_template, redirect, url_for
from flask_login import login_required, current_user

from . import main
from ..auth.forms import PostForm, CommentForm, UpdateProfile
from ..models import Post, Comment, User, Upvote, Downvote


@main.route('/')
def index():
   
    return render_template('index.html')


@main.route('/posts')
@login_required
def posts():
    posts = Post.query.all()
    likes = Upvote.query.all()
    user = current_user
    return render_template('pitch_display.html', posts=posts, likes=likes, user=user)


@main.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        category = form.category.data
        user_id = current_user._get_current_object().id
        post_obj = Post(post=post, title=title, category=category, user_id=user_id)
        post_obj.save()
        return redirect(url_for('main.index'))
    return render_template('pitch.html', form=form)


@main.route('/comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def comment(post_id):
    form = CommentForm()
    post = Post.query.get(post_id)
    user = User.query.all()
    comments = Comment.query.filter_by(post_id=post_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        post_id = post_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(
            comment=comment,
            post_id=post_id,
            user_id=user_id
        )
        new_comment.save()
        new_comments = [new_comment]
        print(new_comments)
        return redirect(url_for('.comment', post_id=post_id))
    return render_template('comment.html', form=form, post=post, comments=comments, user=user)


@main.route('/user')
@login_required
def user():
    username = current_user.username
    user = User.query.filter_by(username=username).first()
    if user is None:
        return ('not found')
    return render_template('profile.html', user=user)


@main.route('/user/<name>/update_profile', methods=['POST', 'GET'])
@login_required
def updateprofile(name):
    form = UpdateProfile()
    user = User.query.filter_by(username=name).first()
    if user is None:
        error = 'The user does not exist'
    if form.validate_on_submit():
        user.bio = form.bio.data
        user.save()
        return redirect(url_for('.profile', name=name))
    return render_template('profile/update_profile.html', form=form)


@main.route('/like/<int:id>', methods=['POST', 'GET'])
@login_required
def upvote(id):
    post = Post.query.get(id)
    vote_mpya = Upvote(post=post, upvote=1)
    vote_mpya.save()
    return redirect(url_for('main.posts'))


@main.route('/dislike/<int:id>', methods=['GET', 'POST'])
@login_required
def downvote(id):
    post = Post.query.get(id)
    vm = Downvote(post=post, downvote=1)
    vm.save()
    return redirect(url_for('main.posts'))

app/templates/account.html
{%extends 'base.html'%} {% block styles %} {{super()}}
<!-- <link
  rel="stylesheet"
  href="{{url_for('static',filename='css/particle.css')}}"
/> -->
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}" /> -->
{% endblock %} {%block content%}
<h2>My account</h2>
<div class="card">
    <img class="rounded-circle" src="{{profile_photo }}">
  <h1>{{current_user.username}}</h1>
  <h1>{{current_user.email}}</h1>
</div>

{%endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{{title}} {% endblock %}
    </title>
    {% block style %}
    <link rel="stylesheet" href="{{css/login.css}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}">
    {% endblock %}
</head>

<body>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}
    {% with messages = get_flashed_messages %}
    {% if messages %}
    {% for message in message %}
    <span>
        {{message}}
    </span>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock %}

</body>

</html>

app/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Create a post</h1>
    <form class="rounded form">
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" placeholder="title" name="title">
        </div>
        <div class="form-group">
            <label>Content</label>
            <textarea type="email" class="form-control" placeholder="content" name="content"></textarea>
        </div>

        <button type="submit" class="d-block mx-auto">Post</button>

</div>
{% endblock %}

app/templates/forms.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %} 

{% block content %}
  <div class="container">
      <form method = "POST" action = "{{url_for('form') }}">
          
      </form>

  </div>

  {% endblock content%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page ,check the url</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}  {% import'bootstrap/wtf.html' as wtf %}
 {% block style %} {{ super() }}
  <!--super() function tells Jinja not to override any code that is defined in the block-->
  <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />
  {% endblock %}
   {% block content %}
      <div class="container-fluid" style="padding:0;margin:0;">
          <p style="font-size: 30px; float: left; height:100vh;width:100vw;background: url('https://images.unsplash.com/photo-1533073526757-2c8ca1df9f1c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80');
          background-repeat: no-repeat;background-size: cover;background-position: center;" class="col-md-12">
            <strong style="float:left; width:500px;font-style: italic;margin-top:120px;">
              <span style="font-size: larger;color:black;">What can you do in 60 sec?......</span><br />
              If  you only had 60 seconds to impress someone. One minute to
              make or break you.How would it end?
            </strong>
            <br>
              <a
                class="btn btn-primary"
                href="{{url_for('auth.signup')}}"
                style="background-color: #002457; margin-top: 300px; font-size: 2rem;"
                ><span aria-hidden="true"> Sign up</span></a>
          
           </p>
         
      </div>
   
    {% endblock %}

app/templates/login.html
{% extends "base.html" %} {% import'bootstrap/wtf.html' as wtf %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}">
{% endblock %}
{% block content %}

  <div class="container">
    <form style = "padding:10px; background-color:rgba(128, 128, 128, 0.336);margin:auto;
    width:70%;" method ="POST" action="login">
      <h2 style="text-align:center;">Log in</h2>
      <div class="form-group">
        <label>Username</label>
        <input type="text" class="form-control" placeholder="Username" name="username">
      </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <button type="submit" class="d-block mx-auto">Login</button>
  
  </div>
{% endblock %}

app/templates/navbar.html
{% import'bootstrap/wtf.html' as wtf %}
<nav class="navbar navbar-default" style="padding:0;margin:0;">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><h2 style="color:rgba(0, 0, 0, 0.596);font-weight:bold;padding:0;margin:auto;font-size: xx-large;">User Stories</h2></a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
        
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        <li><a href="{{ url_for('main.new_post') }}">create post</a></li>
      </ul>
    </div>
</nav>

app/templates/pitch.html
{% extends 'base.html'%}
{% from 'pitch_display_macro.html' import display_pitches%}
{% from 'comment_macro.html' import display_comments%}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/particle.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
{% endblock %}
{% block content %}
<div>{{ display_pitches(posts) }}</div>
<div class="">{{display_comments(comments)}}</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}  {% import'bootstrap/wtf.html' as wtf %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/forms.css')}}" />
{% endblock %}
{% block content %}

<div class="container">
    <form  style = "padding:10px; background-color:rgba(128, 128, 128, 0.336);margin:auto;
    width:70%;">
        <h2 style="text-align:center;"> Create an account with us</h2>
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" placeholder="email" name="email">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <div class="form-group">
            <label for="password"> Confirm Password</label>
            <input type="password" class="form-control" placeholder=" confirm Password" name="confirm password">
        </div>
        <button type="submit" class="d-block mx-auto">Sign up</button>

</div>
{% endblock %}